# Generated by Django 2.2.6 on 2020-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
