# Generated by Django 2.2.6 on 2020-06-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20200609_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tilte',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=50),
        ),
    ]
