# Generated by Django 2.2.6 on 2020-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20200610_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
