# Generated by Django 2.2.6 on 2020-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20200610_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default='1.00', max_digits=50),
        ),
    ]
