# Generated by Django 2.2.6 on 2020-06-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Order',
        ),
    ]
